high_level_planner:
  #high_level_planner:
  ros__parameters:
    use_sim_time: False
    set_orientation: True  # Set intermediate orientations along path from simple 2D planner
    expected_planner_frequency: 1.0
    distance_threshold: 0.125  # Distance in meters from final position to determine success
    planner_plugin: 'GridBased'
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      allow_unknown: true
      tolerance: 0.125
      use_astar: false
      use_final_approach_orientation: false # Use defined goal orientation at final pose
    smoother_type: 'SimpleSmoother'
    simple_smoother:
        tolerance: 2e-10
        max_its: 1001
        w_data: 0.21
        w_smooth: 0.31
        do_refinement: true
        refinement_num: 2
        smoother_timeout: 2.5


high_level_planner_rclcpp_node:
  ros__parameters:
    use_sim_time: False
