mid_level_planner:
  # Mid level planner
  ros__parameters:
    use_sim_time: False
    set_orientation: True  # Set intermediate orientations along path from simple 2D planner
    expected_planner_frequency: 4.0
    lookahead_distance: 1.5    # Distance in meters along path from robot for planner target
    distance_threshold: 0.125  # Distance in meters from final position to determine success
    planner_plugin: 'GridBased'
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      allow_unknown: true
      tolerance: 0.125
      use_astar: false
      use_final_approach_orientation: true

mid_level_planner_rclcpp_node:
  ros__parameters:
    use_sim_time: False
